name: Deploy Laravel Backend to Namecheap

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: debug local files
      - name: List backend folder locally
        run: ls -la $GITHUB_WORKSPACE/backend

      - name: Deploy Laravel backend via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 21098
          source: "backend/*"
          target: "/home/${{ secrets.USERNAME }}/laravelapp/"

      - name: Run remote commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 21098
          script: |
            cd ~/laravelapp/backend
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
